services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: ros2_tut_docker
    privileged: true
    ports:
      - "8080:8080"  # noVNC web interface
    volumes:
      - ./ws:/ws
    environment:
      - DISPLAY=:0
      - VNC_RESOLUTION=1920x1080
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    shm_size: 2048m
    hostname: localhost
    restart: unless-stopped
  novnc:
    image: bonigarcia/novnc:1.2.0
    container_name: novnc
    ports:
      - "6080:6080"
    environment:
      - AUTOCONNECT=true
      - VNC_SERVER=172.17.0.1:5900
