services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_tut_docker
    privileged: true
    ports:
      - "5900:5900"
      - "6080:6080"
    volumes:
      - ./ws:/ws
    environment:
      - DISPLAY=:0
      - VNC_RESOLUTION=1920x1080
    shm_size: 2048m
    hostname: localhost

